//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JsonViewer.Public_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="_PublicSoap", Namespace="http://tempuri.org/")]
    public partial class _Public : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectDataTNSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteDataTNSOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginDomainOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public _Public() {
            this.Url = global::JsonViewer.Properties.Settings.Default.JsonViewer_Public_Service__Public;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectDataTNSCompletedEventHandler SelectDataTNSCompleted;
        
        /// <remarks/>
        public event ExecuteDataTNSCompletedEventHandler ExecuteDataTNSCompleted;
        
        /// <remarks/>
        public event LoginDomainCompletedEventHandler LoginDomainCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectDataTNS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectDataTNS(string inTNSName, string inSQL) {
            object[] results = this.Invoke("SelectDataTNS", new object[] {
                        inTNSName,
                        inSQL});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectDataTNSAsync(string inTNSName, string inSQL) {
            this.SelectDataTNSAsync(inTNSName, inSQL, null);
        }
        
        /// <remarks/>
        public void SelectDataTNSAsync(string inTNSName, string inSQL, object userState) {
            if ((this.SelectDataTNSOperationCompleted == null)) {
                this.SelectDataTNSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectDataTNSOperationCompleted);
            }
            this.InvokeAsync("SelectDataTNS", new object[] {
                        inTNSName,
                        inSQL}, this.SelectDataTNSOperationCompleted, userState);
        }
        
        private void OnSelectDataTNSOperationCompleted(object arg) {
            if ((this.SelectDataTNSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectDataTNSCompleted(this, new SelectDataTNSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteDataTNS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecuteDataTNS(string inConnect, string inSQL) {
            object[] results = this.Invoke("ExecuteDataTNS", new object[] {
                        inConnect,
                        inSQL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteDataTNSAsync(string inConnect, string inSQL) {
            this.ExecuteDataTNSAsync(inConnect, inSQL, null);
        }
        
        /// <remarks/>
        public void ExecuteDataTNSAsync(string inConnect, string inSQL, object userState) {
            if ((this.ExecuteDataTNSOperationCompleted == null)) {
                this.ExecuteDataTNSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDataTNSOperationCompleted);
            }
            this.InvokeAsync("ExecuteDataTNS", new object[] {
                        inConnect,
                        inSQL}, this.ExecuteDataTNSOperationCompleted, userState);
        }
        
        private void OnExecuteDataTNSOperationCompleted(object arg) {
            if ((this.ExecuteDataTNSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteDataTNSCompleted(this, new ExecuteDataTNSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginDomain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] LoginDomain(string inUser, string inPassword) {
            object[] results = this.Invoke("LoginDomain", new object[] {
                        inUser,
                        inPassword});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LoginDomainAsync(string inUser, string inPassword) {
            this.LoginDomainAsync(inUser, inPassword, null);
        }
        
        /// <remarks/>
        public void LoginDomainAsync(string inUser, string inPassword, object userState) {
            if ((this.LoginDomainOperationCompleted == null)) {
                this.LoginDomainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginDomainOperationCompleted);
            }
            this.InvokeAsync("LoginDomain", new object[] {
                        inUser,
                        inPassword}, this.LoginDomainOperationCompleted, userState);
        }
        
        private void OnLoginDomainOperationCompleted(object arg) {
            if ((this.LoginDomainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginDomainCompleted(this, new LoginDomainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SelectDataTNSCompletedEventHandler(object sender, SelectDataTNSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectDataTNSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectDataTNSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExecuteDataTNSCompletedEventHandler(object sender, ExecuteDataTNSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteDataTNSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteDataTNSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LoginDomainCompletedEventHandler(object sender, LoginDomainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginDomainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginDomainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591